import type { GuideCard } from '../types'
import { SettingsMapTable } from './settingsMap'

// Chapter: Pages — Projection, Calendar, Settings (two cards) (2026-09-14 guide spec §5.1).
// Written by lane G4 from research §5.3 P10–P12; every bold label and every `where` segment
// was grepped out of a non-test source before it was written down (spec §5.2).
export const PLANNING_CARDS: GuideCard[] = [
  {
    id: 'page-projection',
    title: 'Projection',
    purpose:
      'A retirement projection from your own records — investable balance, contribution, spend and withdrawal rate — with a fan of simulated paths. Nothing here is saved.',
    to: '/projection',
    views: ['Planning workspace', 'Historical trend'],
    keywords: ['projection', 'forecast', 'retire', 'fire', 'monte carlo', 'fi date'],
    tasks: [
      {
        id: 'projection-assumptions',
        title: 'Adjust an assumption',
        where: 'Projection → Planning workspace → Planning assumptions',
        steps: [
          'Type into **Annual return**, **Monthly contribution**, **Annual spend** or **Withdrawal rate**.',
          'Or into the model knobs: **Horizon (years)**, **Volatility**, **Inflation**, **Contribution growth**.',
          'Blank means derived — the badge names the source: **From your records**, **Settings** or **Planning default**.',
          'Enter 5 for 5%. The chart and the outcomes re-run as you type, and the address carries the scenario.',
        ],
        to: '/projection',
        keywords: ['assumptions', 'return', 'contribution', 'forecast', 'scenario'],
      },
      {
        id: 'projection-use-budgets',
        title: 'Use your budgets as annual spend',
        where: 'Projection → Planning assumptions → Annual spend',
        steps: [
          'Press **Use my budgets** — twelve times the living-category budgets in force this month becomes the annual spend.',
        ],
        to: '/projection',
        keywords: ['budgets', 'annual spend'],
      },
      {
        id: 'projection-retire-month',
        title: 'Set a retirement month',
        where: 'Projection → Planning assumptions → Retires',
        steps: [
          'Type a month for each person — a dashed rule marks it on the chart.',
          'From that month, that person\u2019s take-home, payroll deductions and employer match leave the contribution stream.',
          'Blank means that person works for the whole horizon.',
        ],
        to: '/projection',
        watch: ['Spending stays a household figure — the FI target does not move when one person retires.'],
        keywords: ['retire', 'retirement date', 'stop working'],
      },
      {
        id: 'projection-dollars',
        title: 'Switch between today\u2019s and future dollars',
        where: 'Projection → Projected investable balance',
        steps: ["Pick **Today's dollars** or **Future dollars** — display only; dates, probabilities and targets do not move."],
        to: '/projection',
        keywords: ['inflation', 'nominal', 'real dollars'],
      },
      {
        id: 'projection-pin',
        title: 'Pin and compare scenarios',
        where: 'Projection → Compare your scenarios',
        steps: [
          'Type a label and press **Pin this scenario** — at most three, kept in this browser.',
          'Pinned runs join the chart and the comparison table; **Copy link** shares the live scenario.',
        ],
        to: '/projection',
        keywords: ['pin', 'compare', 'share scenario'],
      },
      {
        id: 'projection-reset',
        title: 'Reset to the derived baseline',
        where: 'Projection → Planning assumptions',
        steps: ['Press **Reset to baseline** — every knob returns to what your records imply.'],
        to: '/projection',
      },
    ],
    more: [
      {
        id: 'projection-window',
        title: 'Change the chart window and axis',
        where: 'Projection → Projected investable balance',
        steps: ['**Next milestone** or **Full horizon**; **Linear** or **Log** — the log axis omits values at or below zero.'],
        to: '/projection',
      },
      {
        id: 'projection-historical',
        title: 'Read the historical trend',
        where: 'Projection → Historical trend',
        steps: [
          'The panel is mounted the first time you open the tab — history never gates the planning model.',
          'Every monthly net-worth snapshot draws as a dot; the span toggle sets how far the fit runs forward.',
          'Under three snapshots there is no fit — the dots stay and the footer says why.',
        ],
        to: '/projection?section=trend',
      },
      {
        id: 'projection-outcomes',
        title: 'Read the outcomes band',
        where: 'Projection → Planning workspace',
        steps: [
          '**FI target** is annual spend ÷ withdrawal rate; **FI ratio** is the investable balance against it.',
          '**Investable balance** is pre-tax, post-tax, taxable and equity from the latest snapshot — cash and liabilities excluded.',
          '**Projected FI date** is the deterministic reach month; the last tile is the share of simulated paths reaching it.',
        ],
        to: '/projection',
      },
    ],
    watch: [
      'Nothing on this page is saved — the stored withdrawal rate lives under Settings → Planning → Plan assumptions.',
      'The probability tile asks whether the target is reached within the horizon, not whether the spending lasts.',
      'RSU vests are not in the derived contribution — raise it by hand to model them.',
      'A volatility of 0 turns the fan off; it is a legitimate value, not an error.',
    ],
  },
  {
    id: 'page-calendar',
    title: 'Calendar',
    purpose:
      'Every dated thing the household’s money touches — vests, paydays, ESPP dates, ex-dividends, tax deadlines, card dates, the monthly reminder and your own events — composed on read.',
    to: '/calendar',
    keywords: ['calendar', 'events', 'deadline', 'payday', 'ics', 'reminder'],
    tasks: [
      {
        id: 'calendar-navigate',
        title: 'Move around the calendar',
        where: 'Calendar',
        steps: [
          'Use ‹ and ›, **Today**, or **Jump to month**.',
          'In the grid, arrows move a day or a week, Home and End the week’s ends, PageUp and PageDown the month.',
          'Switch **Grid** and **List** with the view toggle — the list shows the month on screen, hidden rows dimmed.',
        ],
        to: '/calendar',
        keywords: ['navigate', 'list view', 'grid'],
      },
      {
        id: 'calendar-add-event',
        title: 'Add your own event',
        where: 'Calendar → Add event',
        steps: [
          'Press **Add event**; fill **Date** and **Title**, and **Note (optional)** if you want one.',
          'With two people on the roster, **Person** tags it; **Household** leaves it shared.',
          'Fill **Amount (optional)** and **Direction**, then **Repeats** — and **Until (optional)** when it repeats.',
          'Press **Save event** — the grid lands on that date.',
        ],
        to: '/calendar?add=1',
        watch: ['Without an amount the direction is saved as **No direction** — money out of nothing is not a fact.'],
        keywords: ['custom event', 'reminder', 'add event', 'new event'],
      },
      {
        id: 'calendar-edit-event',
        title: 'Edit or delete your event',
        where: 'Calendar → Grid',
        steps: [
          'Click the chip, press **Edit**, change it, press **Save changes**.',
          '**Delete** offers **Undo** in the toast; the restored event is a new row.',
        ],
        to: '/calendar',
        watch: ['A repeating series is anchored to its start — editing one occurrence edits the series.'],
      },
      {
        id: 'calendar-override',
        title: 'Mark a generated event done, hide it, or enter your figure',
        where: 'Calendar → Grid',
        steps: [
          'Click the chip. A deadline offers **Mark done**, and **Reopen** afterwards.',
          '**Hide** takes any generated event off the grid; **Unhide** from the list view brings it back.',
          'Press **Your figure**, type **Amount you paid**, press **Save figure**; **Use the estimate** clears it.',
        ],
        to: '/calendar',
        keywords: ['done', 'hide event', 'your figure', 'override'],
      },
      {
        id: 'calendar-export-ics',
        title: 'Download these months as a calendar file',
        where: 'Calendar → Add to calendar (.ics)',
        steps: [
          'Press **Add to calendar (.ics)** — the server composes the month on screen with one either side.',
          'The file carries your overrides, your own events and the reminder alarms; it is a snapshot, not a subscription.',
        ],
        to: '/calendar',
        keywords: ['ics', 'download calendar', 'export'],
      },
      {
        id: 'calendar-subscribe',
        title: 'Subscribe a phone or desktop calendar',
        where: 'Settings → Integrations → Calendar feed',
        steps: [
          'Type a label for the device — the box takes “phone, laptop” — and press **New feed link**.',
          'Press **Copy** while the link is on screen: it is shown once. Then press **Done**.',
          'Google: Other calendars, From URL. Apple: File, New Calendar Subscription.',
          'Press **Revoke** on a link when a device is gone.',
        ],
        to: '/settings?section=integrations#calendar',
        watch: ['The link is the credential — anyone holding it can read the feed, amounts included.'],
        keywords: ['subscribe', 'feed', 'phone calendar', 'google calendar', 'apple calendar', 'ical'],
      },
      {
        id: 'calendar-reminder-day',
        title: 'Set the monthly update reminder day',
        where: 'Settings → Integrations → Calendar feed → Monthly update reminder day',
        steps: [
          'Type a day from 1 to 28 — every month has one — and press **Save reminder day**.',
          'The reminder lands on that day each month, on the calendar and in the feed, with an alarm three days before.',
        ],
        to: '/settings?section=integrations#calendar',
        keywords: ['reminder', 'monthly reminder', 'reminder day'],
      },
    ],
    more: [
      {
        id: 'calendar-open-day',
        title: 'Open a day',
        where: 'Calendar → Grid',
        steps: [
          'Click the day number, or the more chip when a day is full; Enter on a focused cell does the same.',
          '**Add event on** that date sits in the drawer; Escape closes it and returns focus to the cell.',
        ],
        to: '/calendar',
      },
      {
        id: 'calendar-follow',
        title: 'Follow an event to its page',
        where: 'Calendar → Grid',
        steps: ['A generated event carries an **Open** link to the page that owns it — a card, a grant, a tax year.'],
        to: '/calendar',
      },
      {
        id: 'calendar-source-health',
        title: 'Read what the calendar could not see',
        where: 'Calendar → Sources',
        steps: ['The source list under the grid names every generator, its status, and the server’s reason when it is not plainly on.'],
        to: '/calendar',
      },
    ],
    watch: [
      'A subscription link is a credential — revoke it when a device is gone.',
      'Done, hide and your figure apply to generated events; your own events are edited directly.',
      'Hidden events are reachable only from the list view — that is where **Unhide** lives.',
    ],
  },
  {
    id: 'page-settings',
    title: 'Settings — Household & Planning',
    purpose:
      'Who the dashboard tracks and what they own — people, accounts, spending categories — plus the year’s contribution limits and the planning assumptions other pages derive from.',
    to: '/settings',
    views: ['Household', 'Planning', 'Account', 'Integrations', 'Data'],
    keywords: ['settings', 'household', 'accounts', 'categories', 'limits', 'people'],
    tasks: [
      {
        id: 'household-add-member',
        title: 'Add a household member',
        where: 'Settings → Household → Household',
        steps: [
          'Type the name under **Add a household member** and press **Add member**.',
          'The person is selectable at once as an owner on accounts, portfolio accounts, paycheck profiles and cards.',
        ],
        to: '/settings?section=household#household',
        keywords: ['partner', 'spouse', 'add person', 'household member'],
      },
      {
        id: 'accounts-add',
        title: 'Add an account',
        where: 'Settings → Household → Accounts',
        steps: [
          'Type the **Account name** and pick the **Group**: Cash, Pre-tax, Post-tax, Taxable, Equity, Other or Liabilities.',
          'Pick the **Owner**, set the **Sort order**, and press **Add account**.',
          'The account appears in the monthly update and in the net-worth charts from the next entry on.',
        ],
        to: '/settings?section=household#accounts',
        watch: ['A Liabilities account holds negative balances — a positive card balance inflates net worth.'],
        keywords: ['add account', 'new account', 'bank account', 'brokerage account', '401k account'],
      },
      {
        id: 'accounts-owner',
        title: 'Assign single or joint ownership',
        where: 'Settings → Household → Accounts',
        steps: [
          'In **Owner**, pick a person to make the account theirs, or **Joint** to leave it shared.',
          'The **Whose** chip on Net worth, Portfolio and Overview reads a person as their own accounts plus the joint ones.',
          'Portfolio accounts have their own **Owner** column under **Portfolio accounts** — the same choice, one table down.',
        ],
        to: '/settings?section=household#accounts',
        watch: ['A new label typed on a transaction or dividend is owned by the primary person until you re-tag it here.'],
        keywords: ['joint', 'ownership', 'owner', 'whose account', 'single owner'],
      },
      {
        id: 'accounts-parent-component',
        title: 'Link component accounts to a parent',
        where: 'Settings → Household → Accounts',
        steps: [
          'On the component, pick the **Parent account** and tick **Component of the parent** — both halves, or the save is refused.',
          'In the monthly update you type the components; the parent is derived and read-only.',
        ],
        to: '/settings?section=household#accounts',
        watch: ['The **Roll-up** column says who sums whom — a component whose parent is retired counts nowhere.'],
        keywords: ['component', 'parent account', 'derived'],
      },
      {
        id: 'categories-add',
        title: 'Add a spending category',
        where: 'Settings → Household → Spending categories',
        steps: [
          'Type the **Category name** and a **Sort order**, then press **Add category**.',
          'Per row: **Edit**, **Retire** or **Delete** — delete works only while a category has no monthly rows.',
        ],
        to: '/settings?section=household#categories',
        keywords: ['category', 'new category', 'spending category'],
      },
      {
        id: 'categories-kind',
        title: 'Set a category’s kind',
        where: 'Settings → Household → Spending categories',
        steps: [
          'Pick **Living**, **Tax** or **Transfer** on the row.',
          'Living left the household; Tax is income tax paid from take-home; Transfer stayed yours.',
          'Only Living counts as spending in the budgets, the savings rate and the projection.',
        ],
        to: '/settings?section=household#categories',
        watch: ['A kind change recomputes every month, chart and projection — set kinds before entering history.'],
        keywords: ['living', 'transfer', 'tax category', 'kind'],
      },
      {
        id: 'limits-enter',
        title: 'Enter contribution limits',
        where: 'Settings → Planning → Contribution limits',
        steps: [
          'Pick the year chip, type each limit, press **Save limits** — or press **Clone from** the year before.',
          'The dashboard ships no figures of its own: a blank box means not entered, and the Paycheck pace meters say so.',
        ],
        to: '/settings?section=planning#limits',
        keywords: ['limits', '401k limit', 'hsa limit', 'irs limits', 'contribution limit'],
      },
      {
        id: 'plan-assumptions',
        title: 'Set the plan assumptions',
        where: 'Settings → Planning → Plan assumptions',
        steps: [
          'Type **Withdrawal rate (% / year)**, **ESPP ticker** and **ESPP discount (%)**, then press **Save assumptions**.',
          'Projection derives its FI target from the rate; ESPP and Paycheck price their figures from the ticker and the discount.',
        ],
        to: '/settings?section=planning#plan-assumptions',
        keywords: ['withdrawal rate', 'swr', 'espp ticker', 'plan assumptions'],
      },
    ],
    more: [
      {
        id: 'household-marriage-date',
        title: 'Set the marriage date',
        where: 'Settings → Household → Household',
        steps: [
          'Type the **Marriage date** and press **Save marriage date** — the net-worth chart marks that month.',
          'Nothing is backfilled: a partner’s accounts and balances start when you enter them.',
          'Filing status is a separate choice, made per year on Taxes.',
        ],
        to: '/settings?section=household#household',
        keywords: ['marriage', 'married', 'wedding'],
      },
      {
        id: 'accounts-retire-delete',
        title: 'Retire or delete an account',
        where: 'Settings → Household → Accounts',
        steps: [
          '**Retire** keeps the history and takes the account out of the monthly update and the charts; **Restore** brings it back.',
          '**Delete** works only while an account has no balances — otherwise the server refuses it and says so.',
        ],
        to: '/settings?section=household#accounts',
        keywords: ['retire account', 'delete account', 'close account'],
      },
      {
        id: 'household-rename',
        title: 'Rename a person',
        where: 'Settings → Household → Household',
        steps: ['Press **Rename**, type the new name, press **Save name**.'],
        to: '/settings?section=household#household',
      },
    ],
    watch: [
      'Delete is refused for accounts with balances and categories with rows — retire those instead.',
      'The primary member can be renamed, but never changed or removed.',
      'Nothing here is per-year except the limits — re-owning an account rewrites how every month reads at once.',
    ],
  },
  {
    id: 'page-settings-data',
    title: 'Settings — Account, Integrations & Data',
    purpose:
      'Your password and appearance, the integrations — prices, assistant, calendar feed — and the data lifecycle: import, snapshots, restore, health, activity.',
    to: '/settings',
    views: ['Household', 'Planning', 'Account', 'Integrations', 'Data'],
    keywords: ['settings', 'backup', 'restore', 'import', 'api key', 'theme', 'password'],
    tasks: [
      {
        id: 'appearance',
        title: 'Change theme, density and landing page',
        where: 'Settings → Account → Appearance',
        steps: [
          'Pick a **Theme** — **System** follows the operating system — a **Density**, **Chart patterns**, and a **Landing page**.',
          'They paint in this browser at once and follow your account at the next sign-in elsewhere.',
        ],
        to: '/settings?section=account#appearance',
        keywords: ['theme', 'dark mode', 'light mode', 'density', 'landing page', 'appearance'],
      },
      {
        id: 'password',
        title: 'Change the password',
        where: 'Settings → Account → Password',
        steps: [
          'Type **Current password**, then **New password** and **Confirm new password**; press **Change password**.',
          'Every other device is signed out; this one stays signed in.',
        ],
        to: '/settings?section=account#password',
        keywords: ['password', 'sign out devices'],
      },
      {
        id: 'price-refresh-schedule',
        title: 'Set the price refresh schedule',
        where: 'Settings → Integrations → Price refresh',
        steps: [
          'Type a five-field cron with day names into **Price refresh cron** and press **Save schedule** — it applies at once.',
          'Press **Refresh now** for a run outside the schedule.',
        ],
        to: '/settings?section=integrations#price-refresh',
        watch: [
          'Keep Mondays covered — the Monday run is what records the weekly performance point.',
          'A schedule that would fire more often than hourly is refused.',
        ],
        keywords: ['cron', 'schedule', 'price refresh', 'scheduler'],
      },
      {
        id: 'assistant-key',
        title: 'Set up the assistant',
        where: 'Settings → Integrations → Assistant',
        steps: [
          'Paste the key into **NVIDIA API key**, pick a **Default model**, press **Save assistant settings**.',
          'Press **Test key** to probe the models; **Remove saved key** falls back to the key in the server’s .env.',
        ],
        to: '/settings?section=integrations#assistant',
        watch: ['Asking the assistant sends the figures behind your question to the provider under this key.'],
        keywords: ['api key', 'assistant setup', 'nvidia', 'model'],
      },
      {
        id: 'import-workbook',
        title: 'Import the workbook',
        where: 'Settings → Data → Import workbook',
        steps: [
          'Choose the **Workbook (.xlsx)**, press **Dry run**, and read the per-sheet diff — nothing is written yet.',
          'Press **Apply import** and confirm the sentence it shows.',
          'If you re-saved the file after choosing it, pick it again.',
        ],
        to: '/settings?section=data#import',
        watch: ['Sheet values overwrite imported rows: taxes work done here for sheet-covered years is reset to the sheet.'],
        keywords: ['import', 'xlsx', 'spreadsheet', 'workbook', 'migrate'],
      },
      {
        id: 'snapshot-now',
        title: 'Write and download a snapshot',
        where: 'Settings → Data → Backups & snapshots',
        steps: [
          'Press **Snapshot now** before an import or a big edit — it writes an export ZIP on the server at once.',
          'Nightly at 23:30 PT the app writes one by itself and keeps the newest fourteen.',
          'Press **Download snapshot (.zip)** to keep a copy off the server.',
        ],
        to: '/settings?section=data#backups',
        keywords: ['backup', 'snapshot', 'export', 'download data'],
      },
      {
        id: 'restore-snapshot',
        title: 'Restore a snapshot',
        where: 'Settings → Data → Restore',
        steps: [
          'Pick a file or a stored snapshot and press **Dry run** — it writes nothing and reports what would change.',
          'A clean dry run asks you to type the snapshot’s date; then press **Restore** and confirm.',
          'A pre-restore point is written first, so the step back is one more restore.',
        ],
        to: '/settings?section=data#restore',
        keywords: ['restore', 'recover', 'rollback'],
      },
      {
        id: 'activity-undo',
        title: 'Undo a change from the log',
        where: 'Settings → Data → Activity',
        steps: [
          'Find the change — newest first — and press **Undo** twice: once to arm, once to fire.',
          'It works while nothing later touched the same rows; **Load more** reaches further back.',
        ],
        to: '/settings?section=data#activity',
        watch: ['Imports and restores are summaries here — they are undone by restoring a snapshot instead.'],
        keywords: ['undo', 'activity log', 'revert', 'change log'],
      },
    ],
    more: [
      {
        id: 'health-checks',
        title: 'Fix a data-health problem',
        where: 'Settings → Data → Data health',
        steps: [
          'Every failing check carries its own fix — a link to the page that owns it, or a button.',
          'A zero-filled month offers **Delete** for that month: press once to arm, again to run. The repair is logged and undoable.',
        ],
        to: '/settings?section=data#health',
        keywords: ['health', 'zero month', 'checks', 'data health'],
      },
      {
        id: 'calendar-feed-pointer',
        title: 'Create a calendar subscription link',
        where: 'Settings → Integrations → Calendar feed',
        steps: ['Feed links are minted, copied once and revoked on the **Calendar feed** card — the Calendar card in this guide walks it.'],
        to: '/settings?section=integrations#calendar',
      },
      {
        id: 'calendar-reminder-pointer',
        title: 'Set the monthly reminder day',
        where: 'Settings → Integrations → Calendar feed',
        steps: ['The reminder day sits on the same **Calendar feed** card — the Calendar card in this guide walks it.'],
        to: '/settings?section=integrations#calendar',
      },
      {
        id: 'system-status',
        title: 'Read the system card',
        where: 'Settings → Data → System',
        steps: [
          '**Data through** names the month each hand-entered feed reaches; **Last backup** and **Recent backups** cover the nightly dump.',
          '**Database size**, **Alembic head** and **Environment** finish it. The card is read-only.',
        ],
        to: '/settings?section=data#system',
      },
    ],
    body: <SettingsMapTable />,
    watch: [
      'An apply that failed may still have written — restore the snapshot you took first.',
      'The cron takes day names (mon-fri); numbers there mean something else.',
      'A key saved on the Assistant card overrides the one in the server’s .env.',
    ],
  },
]
