import type { GuideCard } from '../types'

// Chapter: Pages — Overview, Net worth, Portfolio, Spending, Credit cards, in sidebar order
// (2026-09-14 guide spec §5.1). Written by lane G2 from research §5.3 P1–P5; every bold label
// and every `where` segment verified against the page source before it was written down.
export const TRACKING_CARDS: GuideCard[] = [
  {
    id: 'page-overview',
    title: 'Overview',
    purpose:
      'A read-only briefing: headline tiles, the year so far, the trend, what needs attention and what is coming. No figures are edited here.',
    to: '/',
    keywords: ['overview', 'home', 'dashboard', 'briefing'],
    tasks: [
      {
        id: 'overview-whose',
        title: 'Switch whose figures you see',
        where: 'Overview → Whose',
        steps: [
          'Pick **All**, a person or **Joint** in the sticky row — the chips appear once two people exist.',
          'Net worth, the tiles and holdings follow the choice.',
          'Spending and portfolio performance have no owner dimension; their hints say so rather than filtering.',
        ],
        to: '/',
        keywords: ['owner', 'scope', 'partner', 'joint'],
      },
      {
        id: 'overview-customize',
        title: 'Choose which tiles and cards show',
        where: 'Overview → Customize',
        steps: [
          'Press **Customize** in the title row.',
          'Tick or untick items under **Summary tiles** and **Deeper views**.',
          'Reorder an item with its ↑ or ↓ button; **Reset to defaults** restores the shipped order.',
          'Press **Done** — the layout saves to your account, not to this browser alone.',
        ],
        to: '/',
        watch: ['The last remaining summary tile cannot be unticked — the tile row never goes empty.'],
        keywords: ['layout', 'hide tile', 'reorder'],
      },
      {
        id: 'overview-attention',
        title: 'Act on Needs attention',
        where: 'Overview → Needs attention',
        steps: [
          'Each line in the strip is a condition the data itself proves.',
          'Overdue updates, missing spending, stale quotes, failed tickers, a stale backup and a missing tax year all show here.',
          'Click a line to land on the page that fixes it.',
          'With nothing outstanding the card reads **No outstanding data checks**.',
        ],
        to: '/',
        keywords: ['attention', 'overdue', 'todo'],
      },
      {
        id: 'overview-refresh',
        title: 'Refresh the page',
        where: 'Overview → Refresh',
        steps: [
          'Press **Refresh** in the title row to re-run every feed.',
          'One failed feed shows a banner with **Retry** and leaves the other sections on screen.',
        ],
        to: '/',
        keywords: ['reload', 'refresh overview'],
      },
    ],
    more: [
      {
        id: 'overview-drill',
        title: 'Jump from a chart into its page',
        where: 'Overview → Net worth trend · Recent spending',
        steps: [
          'Click a point on **Net worth trend** — a panel opens with that month\u2019s figure.',
          'Press **Open net worth records** for that month\u2019s accounts.',
          'A **Recent spending** bar opens the same panel with **Open spending**.',
        ],
        to: '/',
        keywords: ['drill', 'chart click'],
      },
      {
        id: 'overview-data-status',
        title: 'Read how fresh the data is',
        where: 'Overview → Data status',
        steps: [
          '**Prices as of** is the oldest quote on file — the staleness clock, not the newest quote.',
          'Balances, spending and net pay each name the month they run through.',
          'A hand-entered feed a whole month behind the balances turns amber.',
        ],
        to: '/',
        keywords: ['freshness', 'stale', 'as of'],
      },
      {
        id: 'overview-up-next',
        title: 'See what is coming',
        where: 'Overview → Up next',
        steps: [
          'Deadlines due within two weeks sort first, then everything by date — five rows, at most one payday.',
          'The line beneath sums what the next 45 days move in and out, including rows the list dropped.',
          'Press **Open calendar** for the rest of the window.',
        ],
        to: '/calendar',
        keywords: ['upcoming', 'events', 'deadlines'],
      },
    ],
    watch: [
      'The portfolio day change is dated from the newest quote — it names that day, not today, unless the quote is today\u2019s.',
      'A month with net pay but no spending entered reads "—" on the Living spending tile, not $0.',
      'Spending and portfolio performance stay household-wide under every Whose chip — the numbers are not filtered.',
    ],
  },
  {
    id: 'page-net-worth',
    title: 'Net worth',
    purpose:
      'Every account’s balance over time and the month-to-month story. Accounts are defined in Settings; balances are entered in the monthly update.',
    to: '/net-worth',
    views: ['Overview', 'Accounts'],
    keywords: ['net worth', 'accounts', 'balances', 'assets', 'liabilities'],
    tasks: [
      {
        id: 'networth-accounts-pointer',
        title: 'Add or change an account',
        where: 'Settings → Household → Accounts',
        steps: [
          'Accounts are added, owned, retired and nested as parent and component in Settings → Household → **Accounts** — see the Settings card in this guide.',
        ],
        to: '/settings?section=household#accounts',
        keywords: ['add account', 'new account'],
      },
      {
        id: 'networth-grain',
        title: 'Read monthly or quarterly',
        where: 'Net worth → Overview',
        steps: [
          'Press **Monthly** or **Quarterly** beside the title.',
          'Under **Quarterly** a ribbon pick snaps to the last quarter that closed at or before it.',
          'A month no quarter has closed by says so rather than drawing an empty chart.',
        ],
        to: '/net-worth',
        keywords: ['quarterly', 'grain', 'monthly'],
      },
      {
        id: 'networth-past-month',
        title: 'Look at a past month’s balances',
        where: 'Net worth → Accounts',
        steps: [
          'Click a month chip in the ribbon — the table and the tiles swap to that month.',
          'The card heading names the month it shows; each chip carries that month’s net worth.',
          'The ribbon’s **Edit ↗** link opens the selected month in the monthly update.',
        ],
        to: '/net-worth?section=accounts',
        keywords: ['history', 'past month', 'balances table'],
      },
      {
        id: 'networth-stack-by',
        title: 'Change how the chart stacks',
        where: 'Net worth → Overview → By group over time',
        steps: [
          'Pick **By group**, **By owner** or **Share %** in the chart’s controls.',
          '**Share %** redraws the stack as percentages of assets and drops the net-worth line.',
          '**By owner** is hidden while the household has one person.',
        ],
        to: '/net-worth',
        keywords: ['stacked chart', 'composition', 'by owner'],
      },
      {
        id: 'networth-what-moved',
        title: 'See what moved this month',
        where: 'Net worth → Overview → What moved',
        steps: [
          'Pick **Groups** or **Accounts** in the card’s controls.',
          'The card compares the viewed snapshot with the one before it, so a ribbon pick moves it.',
          'It appears once two snapshots exist — the first month has nothing to compare with.',
        ],
        to: '/net-worth',
        keywords: ['movers', 'change', 'attribution'],
      },
      {
        id: 'networth-drilldown',
        title: 'Compare accounts over time',
        where: 'Net worth → Accounts → Account drill-down',
        steps: [
          'Click rows in the accounts table, or the chips under the chart, to add an account.',
          'Eight accounts is the cap — a further chip goes disabled instead of swallowing the click.',
          'Each account keeps its colour, so removing one never repaints the survivors.',
        ],
        to: '/net-worth?section=accounts',
        keywords: ['compare accounts', 'drill'],
      },
      {
        id: 'networth-export',
        title: 'Export a chart',
        where: 'Any chart → Export',
        steps: [
          'Press **Export** and choose **PNG**, **Copy image** or **CSV**.',
          '**Table** puts the same numbers under the chart as a table.',
        ],
        to: '/net-worth',
        keywords: ['export', 'csv', 'png', 'download chart'],
      },
    ],
    more: [
      {
        id: 'networth-window',
        title: 'Set the time window',
        where: 'Net worth → All · 1Y · YTD',
        steps: [
          'Pick **All**, **1Y** or **YTD** in the sticky row — both time charts share one axis.',
          'Ctrl and the wheel zoom a chart; the next chip snaps that zoom away.',
        ],
        to: '/net-worth',
        keywords: ['range', 'zoom', 'time window'],
      },
      {
        id: 'networth-owner-scope',
        title: 'Scope to one person',
        where: 'Net worth → Whose',
        steps: [
          'Pick a person or **Joint** — tiles, both charts and the table follow.',
          'A scope that owns no account gets one sentence and a link to **Settings → Accounts**, not zeros.',
        ],
        to: '/net-worth',
        keywords: ['owner', 'joint', 'scope'],
      },
      {
        id: 'networth-weekly-point',
        title: 'Understand the weekly performance point',
        where: 'Net worth · Portfolio',
        steps: [
          'The performance series records one point a week, after Monday’s close, on the product time zone.',
          'A refresh on another weekday keeps quotes fresh and backfills any Monday the host slept through.',
          'Re-importing the workbook overwrites Monday rows wherever the sheet reaches; later rows survive.',
        ],
        keywords: ['weekly', 'monday', 'performance history'],
      },
    ],
    watch: [
      'Liabilities are stored as negative numbers — a card balance typed positive inflates net worth.',
      'A flat month reads neutral, not green — zero is neither good nor bad.',
      'The weekly performance point is Monday-only — a refresh schedule that skips Mondays leaves gaps.',
    ],
  },
  {
    id: 'page-portfolio',
    title: 'Portfolio',
    purpose:
      'Holdings, prices, performance, allocation and income for the household’s investment accounts, with the ledgers that feed them under Manage.',
    to: '/portfolio',
    views: ['Overview', 'Holdings', 'Allocation', 'Income', 'Manage'],
    keywords: ['portfolio', 'holdings', 'stocks', 'shares', 'prices', 'dividends'],
    tasks: [
      {
        id: 'portfolio-refresh',
        title: 'Refresh prices',
        where: 'Portfolio → Refresh prices',
        steps: [
          'Press **Refresh prices** in the title row, or **Refresh now** under Settings → Integrations → **Price refresh**.',
          'The status line then reads the price date and the last run with its trigger.',
          'It also carries the updated and failed counts, and the next scheduled run.',
          'A Monday run also records that week’s performance point.',
        ],
        to: '/portfolio',
        watch: ['The date on the status line is the oldest quote in the book, so one forgotten ticker holds it back.'],
        keywords: ['quotes', 'update prices', 'stale prices'],
      },
      {
        id: 'portfolio-transaction',
        title: 'Record a buy, sell or split',
        where: 'Portfolio → Manage → Transactions',
        steps: [
          'Pick the **Security** and type the **Account** label — one from the list, or a new name.',
          'Pick the **Type** — **Buy**, **Sell** or **Split** — and the **Date**.',
          'Type **Shares**, **Price** and **Fees**; a split takes a **Factor** instead.',
          'Press **Add transaction**; security, account, type and date stay for the next lot.',
          'Use **Duplicate** on a row to seed a repeat, or **Edit** to correct one.',
        ],
        to: '/portfolio?section=manage&tab=transactions',
        watch: [
          'A new account label creates a portfolio account owned by the primary person — re-tag it under Settings.',
          'The money-weighted return column stays blank for a holding whose rows carry no dates.',
        ],
        keywords: ['buy', 'sell', 'split', 'transaction', 'adjust holdings', 'shares'],
      },
      {
        id: 'portfolio-security',
        title: 'Add or edit a security',
        where: 'Portfolio → Manage → Securities',
        steps: [
          'Type the **Ticker**, **Name** and **Industry**, then pick a **Holding type**.',
          'Tick **Manual price** for anything the price feed cannot quote.',
          'Press **Add security**; each row then offers **Edit** and **Delete**.',
          'Editing shows **Active** — untick it to retire a delisted ticker and keep its records.',
        ],
        to: '/portfolio?section=manage&tab=securities',
        watch: ['Delete is refused while a transaction or dividend points at the security.'],
        keywords: ['ticker', 'new security', 'fund', 'deactivate'],
      },
      {
        id: 'portfolio-manual-price',
        title: 'Set a price by hand',
        where: 'Portfolio → Manage → Securities',
        steps: [
          'On a manual-priced row press **Set price**, type the **Price** and press **Save price**.',
          'Refreshes never touch a manual-priced security, so the figure holds until you change it.',
          'Editing such a security also offers **Annual dividend**; on auto-priced ones a refresh owns that field.',
        ],
        to: '/portfolio?section=manage&tab=securities',
        keywords: ['manual price', 'private asset', 'nav'],
      },
      {
        id: 'portfolio-dividend',
        title: 'Log a dividend',
        where: 'Portfolio → Income → Dividends',
        steps: [
          'Pick the **Security**, type the **Account**, then the **Pay date** and the **Amount**.',
          'Press **Add dividend** — security, account and date stay for the next payment.',
          'Type your own rows only for manual-priced holdings and history older than the refresh window.',
        ],
        to: '/portfolio?section=income&tab=dividends',
        watch: ['Deleting a row badged auto cannot be undone — the next refresh writes it back.'],
        keywords: ['dividend', 'income', 'payment'],
      },
      {
        id: 'portfolio-holding-detail',
        title: 'Inspect one holding',
        where: 'Portfolio → Holdings',
        steps: [
          'Click a row — the heading keeps the section name and adds the ticker.',
          'The panel carries that holding’s price history, transactions and income.',
          'Press **Clear selection** to close it.',
        ],
        to: '/portfolio?section=holdings',
        keywords: ['holding detail', 'position'],
      },
      {
        id: 'portfolio-classify',
        title: 'Classify securities for allocation',
        where: 'Portfolio → Allocation → Security classifications',
        steps: [
          'Set each security’s **Asset class**, **Geography** and **Industry**; a **Note** is optional.',
          'Narrow the table with **Unclassified** or **Not reviewed**, or type in **Find a security**.',
          'A filter that matches nothing offers **Show all securities**.',
          'One classification serves every owner and survives refreshes and imports.',
        ],
        to: '/portfolio?section=allocation',
        keywords: ['asset class', 'geography', 'industry', 'classification'],
      },
      {
        id: 'portfolio-targets',
        title: 'Set allocation targets',
        where: 'Portfolio → Allocation → Your allocation targets',
        steps: [
          'Press **Set targets**, or **Edit targets** once a set is saved.',
          'Type a **Target (%)** and a **Tolerance (pp)** per row; **Add category** brings in another.',
          'Press **Save draft** at any total, or **Activate targets** once the rows sum to exactly 100 %.',
          'A saved draft never moves the drift table — the active set does.',
        ],
        to: '/portfolio?section=allocation',
        keywords: ['targets', 'drift', 'rebalance'],
      },
    ],
    more: [
      {
        id: 'portfolio-deactivate',
        title: 'Retire a ticker that keeps failing',
        where: 'Portfolio → Refresh prices',
        steps: [
          'A ticker the feed could not price is listed under the status line; hover it for the reason.',
          'Press **Deactivate** — later refreshes skip it and the Overview stops flagging it.',
          'Bring it back by ticking **Active** on the security under Manage → Securities.',
        ],
        to: '/portfolio',
        keywords: ['delisted', 'failed ticker'],
      },
      {
        id: 'portfolio-benchmarks',
        title: 'Read the performance chart',
        where: 'Portfolio → Overview → Performance',
        steps: [
          'Lines: **Portfolio value**, **Cost basis** and **Same deposits in VOO** — every contribution bought into VOO as it landed, the fair comparison.',
          '**S&P 500 — starting balance only** stays off until you pick it in the legend; it invests just the first week’s balance.',
          'The line under the title says how far ahead of — or behind — the same deposits in VOO the portfolio is over the range you picked.',
          'Ticks along the bottom mark weeks with **Dividends** and **Ex-dividend dates** of securities held then or now; hover one to list them.',
          'Click a legend name to drop a line; the axis refits to what is left.',
          'The **Live** dot appears on the All scope only, because the history is household-wide.',
        ],
        to: '/portfolio',
        keywords: ['benchmark', 'performance', 'voo'],
      },
      {
        id: 'portfolio-dimension',
        title: 'Switch the allocation dimension',
        where: 'Portfolio → Allocation',
        steps: [
          'Pick a dimension in the toolbar — the chart and its member list follow.',
          'A member row’s **Open <TICKER>** button opens that holding under Holdings.',
        ],
        to: '/portfolio?section=allocation',
        keywords: ['allocation', 'dimension', 'asset class'],
      },
      {
        id: 'portfolio-owner',
        title: 'Scope the portfolio to a person',
        where: 'Portfolio → Whose',
        steps: [
          'A person chip narrows the tiles, holdings, allocation, dividends, transactions and realized gains.',
          'Performance, the sparklines and price refresh ignore the chips — they cover the whole household.',
        ],
        to: '/portfolio',
        keywords: ['owner', 'joint', 'scope'],
      },
      {
        id: 'portfolio-import-order',
        title: 'Import first, then edit',
        where: 'Settings → Data → Import workbook',
        steps: [
          'Load history with the workbook importer before typing rows by hand.',
          'A re-import rewrites every row the sheet covers; rows dated past its last date survive.',
        ],
        to: '/settings?section=data#import',
        keywords: ['import', 'workbook', 'overwrite'],
      },
    ],
    watch: [
      'The two benchmark legs answer different questions — read their names before calling a gap outperformance.',
      'A security with transactions or dividends behind it cannot be deleted — deactivate it to retire the ticker.',
      'Auto dividend rows are rewritten by every refresh — a deleted one returns on the next run.',
      'Performance figures need dated transactions; imported rows carry none until you date them.',
    ],
  },
  {
    id: 'page-spending',
    title: 'Spending',
    purpose:
      'Where the money went by month and category, the savings rates, and category budgets. The entries themselves come from the monthly update.',
    to: '/spending',
    views: ['Overview', 'Trends', 'Budgets', 'History'],
    keywords: ['spending', 'budget', 'categories', 'savings rate', 'expenses'],
    tasks: [
      {
        id: 'spending-enter-pointer',
        title: 'Enter a month’s spending',
        where: 'Monthly update → Spending',
        steps: [
          'Spending is typed in the monthly update — **Enter month** opens it; the routine is in this guide’s Routines chapter.',
        ],
        to: '/update?step=spending',
        keywords: ['enter spending', 'record spending'],
      },
      {
        id: 'spending-drill-month',
        title: 'Focus one month',
        where: 'Spending → Overview',
        steps: [
          'Click a bar in the monthly chart, or a chip in the ribbon.',
          'The tiles, the donut, **What changed**, the flow and the budget meters all follow that month.',
          'Press **All months** to release it.',
        ],
        to: '/spending',
        keywords: ['month detail', 'drill month'],
      },
      {
        id: 'spending-flow-window',
        title: 'See where a period went',
        where: 'Spending → Overview → Where <period> went',
        steps: [
          'Pick **Month** or **Year** in the card’s controls.',
          'Hover a node to trace its flows; the card follows whatever month is drilled.',
          'A period with no take-home asks for it instead of drawing an empty flow.',
        ],
        to: '/spending',
        keywords: ['sankey', 'flow', 'where money went'],
      },
      {
        id: 'spending-trends',
        title: 'Compare categories over time',
        where: 'Spending → Trends → Category trends',
        steps: [
          'Leave the view on **Compare** and pick up to three category chips.',
          'A category that has a budget also gets a dashed reference line.',
          '**All categories** swaps in one small chart per category, each with its own vertical scale.',
        ],
        to: '/spending?section=trends',
        keywords: ['trend', 'category over time'],
      },
      {
        id: 'spending-heatmap',
        title: 'Read the month by category heatmap',
        where: 'Spending → History → Month × category heatmap',
        steps: [
          'Pick **Absolute**, **Row** or **vs average** for the colour scale.',
          'Categories with nothing recorded are folded away until you show the dormant rows.',
          'Click a cell — the panel that opens carries **Open monthly entries** for that month.',
        ],
        to: '/spending?section=history',
        keywords: ['heatmap', 'history'],
      },
      {
        id: 'spending-budget-seed',
        title: 'Seed budgets from your averages',
        where: 'Spending → Budgets',
        steps: [
          'With no budgets yet, press **Start from my averages**.',
          'It needs three complete months; the note under a disabled button says how many you have.',
          'One dated budget per living category is written; the toast offers **Undo** for the whole batch.',
          'Once budgets exist the button becomes **Re-seed from averages** and asks you to confirm first.',
        ],
        to: '/spending?section=budgets',
        keywords: ['budget seed', 'averages', 'default budgets'],
      },
      {
        id: 'spending-budget-set',
        title: 'Set or change one budget',
        where: 'Spending → Budgets',
        steps: [
          'Press **Set budget** on a row that has none, or **Edit budget** on one that does.',
          'Type the **Monthly budget** and pick **Effective from** — it defaults to the focused month.',
          'Press **Save**; the editor stays open and lists the dated history it just wrote.',
        ],
        to: '/spending?section=budgets',
        watch: ['An effective month in the past changes what that era’s budget was, not only today’s.'],
        keywords: ['set budget', 'edit budget', 'monthly budget'],
      },
      {
        id: 'spending-budget-end',
        title: 'End a budget',
        where: 'Spending → Budgets',
        steps: [
          'Open the editor, clear the **Monthly budget** box and press **Save**.',
          'The budget ends from that effective month on; earlier months keep theirs.',
        ],
        to: '/spending?section=budgets',
        keywords: ['remove budget', 'stop budget'],
      },
    ],
    more: [
      {
        id: 'spending-yearly',
        title: 'Read the yearly rollups',
        where: 'Spending → History → Yearly rollups',
        steps: [
          'Every year with anything entered gets a column, category by category.',
          'Read **Months matched** first: it says how many months the four summary rows stand on.',
          'They can cover fewer months than **Total** does, so the two are not meant to reconcile.',
        ],
        to: '/spending?section=history',
        keywords: ['yearly', 'rollup', 'savings rate'],
      },
      {
        id: 'spending-movers',
        title: 'Read What changed',
        where: 'Spending → Overview → What changed',
        steps: [
          'The five biggest category moves for the focused month, one row each.',
          'Columns compare the month with the prior one, with the 12-month average, and with budget where one exists.',
          'Spending up is red — the arrow says which way it moved, the colour whether that is good.',
        ],
        to: '/spending',
        keywords: ['movers', 'what changed', 'biggest moves'],
      },
      {
        id: 'spending-export',
        title: 'Export a chart',
        where: 'Any chart → Export',
        steps: ['Press **Export** and choose **PNG**, **Copy image** or **CSV**; **Table** puts the numbers under the chart.'],
        to: '/spending',
        keywords: ['export', 'csv', 'png'],
      },
    ],
    watch: [
      'Living spending leaves out categories of kind Tax and Transfer — the kinds are set in Settings.',
      'Changing a category’s kind recomputes every month, chart and projection that reads it.',
      'The 12-month comparison counts only months somebody entered — an empty month lowers the count, not the average.',
      'Spending is never pre-filled from last month; balances are.',
    ],
  },
  {
    id: 'page-credit-cards',
    title: 'Credit cards',
    purpose:
      'Which card to use for what, what each is worth after its fee, and the household’s credit lines — all from the Manage roster.',
    to: '/credit-cards',
    views: ['Rewards', 'Credit lines', 'Manage'],
    keywords: ['credit card', 'cards', 'rewards', 'points', 'annual fee', 'credit line'],
    tasks: [
      {
        id: 'cards-add',
        title: 'Add a card',
        where: 'Credit cards → Manage → Card roster',
        steps: [
          'Press **+ Add card** in the title row — Manage opens with the name box focused.',
          'Fill **Card name**, **Annual fee**, **Rewards currency** and **Point value (¢)** — cents per point, 1 for cash back.',
          'Pick the **Owner**, list any **Authorized users**, set **Opened** and the **Linked liability account**.',
          'Press **Add card**; the roster lists it and the matrix grows a column.',
        ],
        to: '/credit-cards?section=manage',
        keywords: ['new card', 'open a card', 'add credit card'],
      },
      {
        id: 'cards-opened-date',
        title: 'Set the opened date',
        where: 'Credit cards → Manage → Opened',
        steps: [
          'Type the day the card was opened.',
          'It dates the anniversary, the annual fee and any anniversary-cadence credit on the calendar.',
          'The year-two anniversary event also notes that the card falls off 5/24.',
        ],
        to: '/credit-cards?section=manage',
        watch: ['Without it there is no fee, anniversary or anniversary-reset event at all — the roster names every undated card.'],
        keywords: ['anniversary', 'opened', '5/24'],
      },
      {
        id: 'cards-owner',
        title: 'Choose who holds a card',
        where: 'Credit cards → Manage → Owner',
        steps: [
          'Pick a person in **Owner**, or pick **Joint** for a card you both use — a new card starts on the primary person.',
          'Rewards, Credit lines and the tiles then follow the **Whose** chips.',
          'Manage is the one view the chips never narrow, because it is where ownership is edited.',
        ],
        to: '/credit-cards?section=manage',
        keywords: ['joint card', 'ownership', 'whose card'],
      },
      {
        id: 'cards-category-add',
        title: 'Add a reward category',
        where: 'Credit cards → Manage → Categories & weights',
        steps: [
          'Type the **Category name**.',
          'Map it to a **Spending category (for auto weight)**, or type an **Annual spend override**.',
          'Use **Pin to card** to force the answer for that row, then press **Add category**.',
        ],
        to: '/credit-cards?section=manage',
        watch: ['A row with neither a mapping nor an override stays out of every dollar figure on the page.'],
        keywords: ['reward category', 'weight'],
      },
      {
        id: 'cards-multipliers',
        title: 'Fill in the rewards matrix',
        where: 'Credit cards → Rewards → Rewards matrix',
        steps: [
          'Press **Edit multipliers**, then click the cell where a card meets a category.',
          'Type the **Multiplier**, plus a **Condition note** or a **Monthly bonus cap** where they apply.',
          '**Clear cell** blanks it back to N/A, which keeps the card out of that row’s answer.',
          'Press **Save multipliers** — one save writes every cell you changed.',
          'The **Multiplier** and **Effective %** buttons change the number shown, never the winner.',
        ],
        to: '/credit-cards',
        keywords: ['multiplier', 'matrix', 'best card', 'points per dollar'],
      },
      {
        id: 'cards-detail',
        title: 'Open a card’s detail',
        where: 'Credit cards → Rewards matrix',
        steps: [
          'Click the card’s name in the matrix column header.',
          'The detail carries its recurring credits, its rewards, the credit line and utilization.',
          'The drill deliberately ignores the **Whose** chips — the verdict is about the whole lineup.',
          'Press **Back to matrix** to return.',
        ],
        to: '/credit-cards',
        keywords: ['card detail', 'is it worth keeping'],
      },
      {
        id: 'cards-credit-add',
        title: 'Track a recurring credit or benefit',
        where: 'Credit cards → Rewards → Recurring credits',
        steps: [
          'Type the **Credit label** and its yearly value, then press **Add credit**.',
          'Toggle **Resets Jan 1** or **Resets on anniversary** to date its reset on the calendar.',
          'Toggle **Counts ✓** or **Ignored** to decide whether it enters the net-after-fee figure.',
        ],
        to: '/credit-cards',
        watch: ['An anniversary reset needs the card’s opened date before it can reach the calendar.'],
        keywords: ['credit', 'benefit', 'statement credit', 'perk'],
      },
      {
        id: 'cards-limit-add',
        title: 'Record a credit-limit change',
        where: 'Credit cards → Rewards → Credit line',
        steps: [
          'In the card’s detail, type the effective date, the **New limit** and a note.',
          'Press **Add** — the newest event by date becomes the card’s current line.',
          'It then feeds the total credit line tile, the **Credit line history** chart and utilization.',
        ],
        to: '/credit-cards',
        watch: ['One event per card per date — delete the existing row before re-dating a change.'],
        keywords: ['credit limit', 'limit increase', 'cli'],
      },
    ],
    more: [
      {
        id: 'cards-categories-seed',
        title: 'Start with the spreadsheet’s categories',
        where: 'Credit cards → Manage → Categories & weights',
        steps: [
          'While the list is still empty, press **Start with the spreadsheet\'s categories**.',
          'The standard rows appear in order, ready to map or override.',
        ],
        to: '/credit-cards?section=manage',
        keywords: ['seed categories', 'default categories'],
      },
      {
        id: 'cards-archive-delete',
        title: 'Archive or delete a card',
        where: 'Credit cards → Manage → Card roster',
        steps: [
          '**Archive** keeps the history and takes the card out of the matrix, the tiles and the chart.',
          '**Unarchive** puts it back.',
          '**Delete** removes it; the toast’s **Undo** restores the card, its credits and its limit events.',
        ],
        to: '/credit-cards?section=manage',
        keywords: ['close card', 'archive card', 'delete card'],
      },
      {
        id: 'cards-utilization',
        title: 'Read utilization',
        where: 'Credit cards → Rewards → Utilization',
        steps: [
          'It needs a **Linked liability account** with a balance in the latest snapshot, and a current limit.',
          'The line reads balance of limit as a percentage and names the month it read.',
          'Balances are stored negative; the sign is handled for you.',
        ],
        to: '/credit-cards',
        keywords: ['utilization', 'balance', 'credit usage'],
      },
      {
        id: 'cards-hide-category',
        title: 'Hide or reorder a category',
        where: 'Credit cards → Manage → Categories & weights',
        steps: [
          '**Hide** takes a row out of the matrix and keeps its cells; **Show** brings it back.',
          'Drag the grip, or focus it and press the up and down arrows, to reorder.',
        ],
        to: '/credit-cards?section=manage',
        keywords: ['hide category', 'reorder', 'matrix rows'],
      },
    ],
    watch: [
      'The reward tiles read "—" until a category carries a weight — a matrix with no weights values every card at $0.',
      'Deleting a card can be undone, but its matrix multipliers are not restored.',
      'Cards are dashboard-only — a workbook import never touches them.',
    ],
  },
]
