import type { GuideCard } from '../types'

// Chapter: Pages — the Income group and Taxes, in sidebar order (2026-09-14 guide spec §5.1).
// Written by lane G3 from research §5.3 P6–P9; every bold label and Where segment verified
// against source before it was bolded (spec §5.2), and every trap is a rule the page does not
// already print for itself (§5.3 rule 6).
export const INCOME_CARDS: GuideCard[] = [
  {
    id: 'page-paycheck',
    title: 'Paycheck',
    purpose:
      'One person’s paycheck as the server computes it from their profile — the breakdown, where it goes, contribution pace, and a sandbox for changes.',
    to: '/paycheck',
    views: ['Summary', 'Try changes', 'Profiles'],
    keywords: ['paycheck', 'salary', 'net pay', 'withholding', 'contributions', 'hsa', '401k'],
    tasks: [
      {
        id: 'paycheck-profile-add',
        title: 'Add a paycheck profile',
        where: 'Paycheck → Profiles → Profile history',
        steps: [
          'Fill **Effective date**, **Annual salary** and **Pay periods per year** — the form refuses to save without all three.',
          'Type the contribution percents, **Withholding %**, **Dental & vision**, **HSA** and **HSA coverage**.',
          'Open **Employer 401(k) match** and **Employer HSA contribution** for the employer side.',
          'Press **Add profile** — the breakdown, the flow and the pace meters recompute from it.',
        ],
        to: '/paycheck?section=profiles',
        watch: ['A blank percent or money box saves as a real zero — every box arrived pre-filled, so clearing one is a decision.'],
        keywords: ['new profile', 'set up paycheck', 'manage paycheck'],
      },
      {
        id: 'paycheck-profile-carry-forward',
        title: 'Record a raise or an election change',
        where: 'Paycheck → Profiles → Profile history',
        steps: [
          'The form opens pre-filled from the newest profile, with an empty date and no note.',
          'Change only what moved, type the new **Effective date**, and press **Add profile**.',
          'The old row stays as history — nothing is overwritten.',
        ],
        to: '/paycheck?section=profiles',
        keywords: ['raise', 'new salary', 'election change', 'contribution change'],
      },
      {
        id: 'paycheck-person',
        title: 'Switch person',
        where: 'Paycheck → Whose',
        steps: [
          'Press a person chip in the sticky row — a paycheck belongs to one person.',
          'There is no All and no Joint here; the breakdown, flow, pace and history all follow the chip.',
          'Switching drops a pinned profile and any scenario — they belong to the person you left.',
        ],
        to: '/paycheck',
        keywords: ['partner paycheck', 'person', 'whose paycheck'],
      },
      {
        id: 'paycheck-pin-profile',
        title: 'Look at a past profile',
        where: 'Paycheck → Profiles → Profile history',
        steps: [
          'Press a row’s date chip — the page moves to **Summary** and reads that profile.',
          'Press **Show the current profile** to return to the one in force today.',
        ],
        to: '/paycheck?section=profiles',
        keywords: ['history', 'old profile', 'pin'],
      },
      {
        id: 'paycheck-try-it',
        title: 'Try a change without saving',
        where: 'Paycheck → Try changes',
        steps: [
          'Drag a slider or type a figure — the server recomputes the whole check as you go.',
          'Switch **Per check**, **Monthly** or **Annual** to compare against the real check.',
          'Chips: **Max 401(k)**, **Max HSA**, **Max ESPP**, **Stop ESPP** — a disabled one names the limit to enter first.',
          'Nothing here is saved — **Reset to actual** puts every knob back.',
          'The address carries the scenario, so **Copy link** shares exactly what you see.',
        ],
        to: '/paycheck?section=changes',
        keywords: ['what if', 'sandbox', 'try changes', 'simulate paycheck'],
      },
      {
        id: 'paycheck-apply-scenario',
        title: 'Turn a scenario into a profile',
        where: 'Paycheck → Try changes',
        steps: [
          'Press **Save as profile effective <date>…** — Profiles opens with the form filled and focused.',
          'Check every box, then press the form’s own **Add profile**; that is the only write.',
        ],
        to: '/paycheck?section=changes',
        keywords: ['apply scenario', 'save scenario'],
      },
      {
        id: 'paycheck-withholding-split',
        title: 'Enter the withholding split',
        where: 'Paycheck → Profiles → Withholding split (optional)',
        steps: [
          'Open the disclosure and type **Federal withholding %** and **State withholding %** from a paystub.',
          'Taxes then splits its balance into **Federal balance**, **California balance** and **Payroll taxes**, each with its own remedy.',
        ],
        to: '/paycheck?section=profiles',
        watch: ['Blank here means not entered, not zero — the only two boxes on this form that work that way.'],
        keywords: ['withholding split', 'federal withholding', 'state withholding'],
      },
      {
        id: 'paycheck-pace',
        title: 'Read the contribution pace meters',
        where: 'Paycheck → Summary → Contribution pace',
        steps: [
          'Each meter fills solid to what is in so far, then dimmed to where the year lands.',
          'A row with no limit entered draws no meter — it links to Settings to enter one.',
          'The ESPP row appears only once the profile contributes to ESPP.',
        ],
        to: '/paycheck',
        keywords: ['pace', 'limit', 'on track', 'max out'],
      },
    ],
    more: [
      {
        id: 'paycheck-edit-delete',
        title: 'Edit or delete a profile',
        where: 'Paycheck → Profiles → Profile history',
        steps: [
          'Press **Edit** on a row, change it, and press **Save profile**.',
          '**Delete** asks once; the page falls back to the profile in force.',
        ],
        to: '/paycheck?section=profiles',
      },
      {
        id: 'paycheck-read-breakdown',
        title: 'Read the per-check breakdown',
        where: 'Paycheck → Summary → Per-check breakdown',
        steps: [
          'Gross, each deduction and the net, in the order payroll applies them.',
          'The employer match is printed apart — it never passes through the check.',
        ],
        to: '/paycheck',
      },
      {
        id: 'paycheck-household-tile',
        title: 'See both take-home figures at once',
        where: 'Paycheck → Summary → Household take-home',
        steps: [
          'Give each person a profile in force today — the tile appears once both have one.',
          'It never narrows to one person, so it answers a different question from the chip.',
        ],
        to: '/paycheck',
      },
      {
        id: 'paycheck-monthly-net-pointer',
        title: 'Enter actual monthly take-home',
        where: 'Monthly update → Spending',
        steps: ['Actual take-home is typed in the monthly update’s **Spending** step — see the Monthly update card in this guide.'],
        to: '/update?step=spending',
        watch: ['This page’s monthly net is a profile-based estimate, not the take-home you entered for the month.'],
      },
    ],
    watch: [
      'A profile belongs to one person — there is no All or Joint on this page.',
      'Blank percent and money boxes save as a real zero; only the withholding split reads blank as not entered.',
      'Percents that together exceed 100 % warn but save — one box over 100 is refused.',
      'Deleting a profile asks once and cannot be undone.',
    ],
  },
  {
    id: 'page-comp',
    title: 'Comp',
    purpose:
      'RSU grants and the vesting schedule they generate, focal-year history and the total-comp trajectory — one set for the household, not per person.',
    to: '/comp',
    views: ['Summary', 'Vesting', 'Manage'],
    keywords: ['comp', 'rsu', 'grant', 'vest', 'vesting', 'equity', 'focal', 'total comp'],
    tasks: [
      {
        id: 'comp-grant-add',
        title: 'Add an RSU grant',
        where: 'Comp → Manage → RSU grants',
        steps: [
          'Pick the **Kind** — **New hire** or **Refresh**. It carries the cliff, so there is no cliff box.',
          'Fill **Label**, **Grant focal year**, **Shares**, **Price at grant**, **First vest** and **Vest rounding**.',
          'Press **Add grant** — the schedule, the tiles and the calendar’s vest events are all computed from it.',
        ],
        to: '/comp?section=manage',
        watch: ['The kind sets the cliff percentage, never the date — a new-hire grant filed as a refresh vests 6.25 % on its first date instead of 25 %, and runs three quarters longer.'],
        keywords: ['add grant', 'add vest', 'new grant', 'rsu grant'],
      },
      {
        id: 'comp-grant-seed',
        title: 'Seed a grant from a focal year',
        where: 'Comp → Manage → RSU grants',
        steps: [
          'A focal year holding **Refresh RSUs** and a **Grant price**, with no grant yet, offers a chip naming both.',
          'Press it — the form fills and nothing is saved. Check the boxes, then press **Add grant**.',
        ],
        to: '/comp?section=manage',
        watch: ['The chip truncates a fractional share count, because a grant counts whole shares — read it before saving.'],
        keywords: ['seed grant', 'refresh grant'],
      },
      {
        id: 'comp-focal-add',
        title: 'Record a focal year',
        where: 'Comp → Manage → Focal history',
        steps: [
          'Fill **Focal year** and **Current base** — the two the form will not save without.',
          'Add **New base**, **Unvested RSUs**, **Unvested price**, **Refresh RSUs** and **Grant price** as the letter gives them.',
          'Press **Add event**; a stored row is then changed with **Edit** and **Save event**.',
        ],
        to: '/comp?section=manage',
        watch: ['One row per focal year — a second row for a year already recorded is refused.'],
        keywords: ['focal', 'annual review', 'base salary', 'comp event', 'focal information'],
      },
      {
        id: 'comp-vesting-read',
        title: 'Read the vesting schedule',
        where: 'Comp → Vesting → Vesting schedule',
        steps: [
          'Start with the **Next vest**, **Unvested** and **Vested this year** tiles.',
          'Press a vest date in the table to expand its per-grant tranches; opening another folds the first.',
          'Nothing here is stored — every row is recomputed from the grants on each read.',
        ],
        to: '/comp?section=vesting',
        keywords: ['vesting', 'schedule', 'next vest', 'unvested'],
      },
      {
        id: 'comp-grant-edit-delete',
        title: 'Edit or delete a grant',
        where: 'Comp → Manage → RSU grants',
        steps: [
          'Press **Edit** on a row, change it, and press **Save grant**.',
          '**Delete** removes it at once with no confirm — the toast’s **Undo** re-creates it.',
        ],
        to: '/comp?section=manage',
        keywords: ['delete grant', 'edit grant'],
      },
    ],
    more: [
      {
        id: 'comp-columns',
        title: 'Show entered or computed columns',
        where: 'Comp → Manage → Focal history',
        steps: ['Pick **Entered**, **Computed** or **All** under **Columns** — a view choice, and not saved.'],
        to: '/comp?section=manage',
      },
      {
        id: 'comp-tc-read',
        title: 'Read the total-comp chart',
        where: 'Comp → Summary',
        steps: ['One bar per focal year, drawn from **Focal history** — a year with no row has no bar.'],
        to: '/comp',
      },
    ],
    watch: [
      'Comp is not per person — there is no owner chip, and grants and focal history are one household set.',
      'A grant whose shares or price no longer match its focal row raises a drift note — the schedule follows the grant.',
      'With no employer ticker in Settings → Planning → Plan assumptions, every future vest is unvalued.',
      'Deleting a focal row asks once and cannot be undone; deleting a grant can be undone from its toast.',
    ],
  },
  {
    id: 'page-espp',
    title: 'ESPP',
    purpose:
      'Offerings, purchase lots, sales and the $25,000 limit chain for the employee stock purchase plan — priced from the employer ticker set in Settings.',
    to: '/espp',
    views: ['Summary', 'Lots', 'Purchase model'],
    keywords: ['espp', 'offering', 'lots', 'purchase', 'discount', '25k limit'],
    tasks: [
      {
        id: 'espp-offering-add',
        title: 'Add an offering — a new subscription period',
        where: 'ESPP → Lots → Subscription offerings',
        steps: [
          'Type **Offering start**, the enrollment date, and the **Subscription price** it fixed; **Offering notes** are optional.',
          'Press **Add offering**.',
          'A subscription reset is another row — add it and every period after it re-prices.',
        ],
        to: '/espp?section=lots',
        keywords: ['offering', 'subscription period', 'enrollment', 'new espp period', 'reset'],
      },
      {
        id: 'espp-close-chip',
        title: 'Use the close price for the start date',
        where: 'ESPP → Lots → Subscription offerings',
        steps: [
          'Type the start date first — a chip then offers the last stored close on or before it.',
          'Press **Use** to copy it into **Subscription price**; it is never filled in for you.',
        ],
        to: '/espp?section=lots',
        watch: ['The chip needs an employer ticker whose stored prices reach that date.'],
        keywords: ['close price', 'subscription price'],
      },
      {
        id: 'espp-lot-add',
        title: 'Add a purchase lot',
        where: 'ESPP → Lots',
        steps: [
          'Type the **Purchase date** — the offering covering it fills **Subscription** and **Qualifying date**.',
          'Type **Shares** and **FMV**; leave **Purchase price** blank to have it derived at the plan discount.',
          'Press **Add lot**.',
        ],
        to: '/espp?section=lots',
        watch: ['A purchase date no offering covers pre-fills neither box — type the subscription price and the qualifying date yourself.'],
        keywords: ['lot', 'purchase', 'espp buy', 'shares bought'],
      },
      {
        id: 'espp-lot-sold',
        title: 'Mark a lot sold',
        where: 'ESPP → Lots',
        steps: [
          'Press **Edit** on the lot, type **Sold date** and **Sold price**, then press **Save lot**.',
          'To un-sell it, empty both boxes and save again.',
          'A sold row is then measured at its sale price; every other row at the live quote.',
        ],
        to: '/espp?section=lots',
        watch: ['A sold lot loses its Model sale link and can no longer be picked as a what-if leg.'],
        keywords: ['sell espp', 'sold lot', 'disposition', 'sale'],
      },
      {
        id: 'espp-model-sale',
        title: 'Model selling a lot',
        where: 'ESPP → Lots',
        steps: [
          'Press **Model sale** on an unsold row.',
          'Taxes opens in **What-if** with the whole lot as one sale leg.',
          'The leg is hypothetical — nothing is written, on either page.',
        ],
        to: '/espp?section=lots',
        keywords: ['tax on espp sale', 'model sale'],
      },
      {
        id: 'espp-purchase-model',
        title: 'Model the year’s purchases and the $25k limit',
        where: 'ESPP → Purchase model',
        steps: [
          'Press the year chip you want to model.',
          'Leave **Subscription price**, **Purchase FMV** and **Carry-forward** blank to resolve them, or type one to override the year.',
          'Edit **Base**, **Additional** and **Contrib %** per period, then press **Save & recalculate**.',
          'The meter draws one bar per period against $25,000; every figure under it is the server’s.',
        ],
        to: '/espp?section=purchase',
        watch: ['An edited cell does not reach the chain until you save — the card counts the periods still pending.'],
        keywords: ['25k', 'limit', 'purchase model', 'contribution percent'],
      },
      {
        id: 'espp-plan-settings',
        title: 'Set the plan discount and ticker',
        where: 'Settings → Planning → Plan assumptions',
        steps: ['Type the **ESPP ticker** and **ESPP discount (%)** — without both, lots can be neither priced nor derived.'],
        to: '/settings?section=planning#plan-assumptions',
        keywords: ['espp discount', 'employer ticker'],
      },
    ],
    more: [
      {
        id: 'espp-offering-edit',
        title: 'Edit or delete an offering',
        where: 'ESPP → Lots → Subscription offerings',
        steps: ['Press **Edit** or **Delete** on a row — every period that offering covered re-prices.'],
        to: '/espp?section=lots',
      },
      {
        id: 'espp-reset-period',
        title: 'Reset a stored period',
        where: 'ESPP → Purchase model',
        steps: ['Press **Reset** on a stored row to drop your figures and return it to derived values.'],
        to: '/espp?section=purchase',
      },
      {
        id: 'espp-read-charts',
        title: 'Change what the Summary charts show',
        where: 'ESPP → Summary → Lot anatomy',
        steps: [
          'Toggle **Dollars** or **Per share** on **Lot anatomy** — the same split, a different scale.',
          'Pick a **History window** chip on the price chart; a window longer than the stored history is shut.',
        ],
        to: '/espp',
      },
    ],
    watch: [
      'A capped purchase refunds the leftover cash and carries nothing into the next period.',
      'With no employer ticker in Settings → Planning → Plan assumptions, nothing on this page has a market value.',
      'Deleting an offering or a lot asks once and cannot be undone.',
    ],
  },
  {
    id: 'page-taxes',
    title: 'Taxes',
    purpose:
      'The year’s tax as the engine computes it from your inputs and bracket tables — totals, marginal rates, will-I-owe, and a what-if sandbox.',
    to: '/taxes',
    views: ['Summary', 'What-if', 'Inputs', 'Tax tables'],
    keywords: ['taxes', 'tax', 'brackets', 'irs', 'refund', 'owe', 'filing', 'calculate taxes'],
    tasks: [
      {
        id: 'taxes-year-create',
        title: 'Create a tax year',
        where: 'Taxes → New tax year…',
        steps: [
          'Press **New tax year…** in the title row, type the year, and press **Create year**.',
          'Then set its filing status and check the copied figures against this year’s published tables.',
        ],
        to: '/taxes',
        keywords: ['new tax year', 'create year', 'next year'],
      },
      {
        id: 'taxes-filing-status',
        title: 'Set the filing status',
        where: 'Taxes → Filing status',
        steps: [
          'Pick **Single**, **Married filing jointly** or **Married filing separately** in the sticky row.',
          'The year then needs bracket tables for that status before the engine will price it.',
        ],
        to: '/taxes',
        watch: ['Married filing separately does not model California community-income splitting — treat its state figures as unreliable.'],
        keywords: ['married', 'joint', 'single', 'filing status'],
      },
      {
        id: 'taxes-tables',
        title: 'Enter bracket tables',
        where: 'Taxes → Tax tables',
        steps: [
          'Pick the status tab, then the jurisdiction: **Federal**, **State**, **Medicare**, **Social Security**, **Disability** or **Capital gains**.',
          'Press **Add bracket** per row, then type the rate as a percent and the income it starts at.',
          'Press **Save** — each table saves on its own, and twelve rows is the most one holds.',
          'Saving a table with no rows deletes it, after a confirm.',
        ],
        to: '/taxes?section=tables',
        keywords: ['brackets', 'bracket tables', 'rates', 'thresholds', 'ftb'],
      },
      {
        id: 'taxes-inputs',
        title: 'Enter the year’s inputs',
        where: 'Taxes → Inputs → Tax inputs',
        steps: [
          'Type the line items under **Ordinary income**, **Deductions** and **Capital gains**.',
          'Press **Apply** on a chip to take its offer into the box — that alone saves nothing.',
          'Press **Save inputs**, or Ctrl+Enter — only the cells you changed are written.',
          'Clearing a box and saving unsets that input; a box you never touched is never sent.',
        ],
        to: '/taxes?section=inputs',
        keywords: ['inputs', 'w-2', 'deductions', 'line items', 'tax inputs'],
      },
      {
        id: 'taxes-will-i-owe',
        title: 'See whether you will owe',
        where: 'Taxes → Summary → Will I owe?',
        steps: [
          'Read the projected tax, the projected withholding and the balance between them.',
          'With a withholding split on the paycheck profile, the balance splits into **Federal balance**, **California balance** and **Payroll taxes**.',
          'Each side then names its own remedy per remaining check — W-4 line 4c federally, DE 4 for California.',
          'Open **How this is estimated** for the safe-harbour notes and the assumptions behind the figure.',
        ],
        to: '/taxes',
        watch: ['A blank balance means the engine refused for want of tables — not that you are even.'],
        keywords: ['owe', 'refund', 'withholding', 'safe harbor', 'w-4', 'balance due'],
      },
      {
        id: 'taxes-whatif-sale',
        title: 'Model a stock sale',
        where: 'Taxes → What-if',
        steps: [
          'Press **Add sale**, pick the holding, type the shares, and leave the price blank for the latest quote.',
          'Press **Long** or **Short** on the leg to switch the rate it is taxed at.',
          'Or press **Add ESPP sale** and pick an unsold lot.',
          'Read the change in total tax and take-home; nothing is stored, and the address carries the scenario.',
        ],
        to: '/taxes?section=whatif',
        watch: ['Every sale is priced at average cost — the app keeps no lot-level basis, so a specific-lot sale cannot be modelled.'],
        keywords: ['sell shares', 'capital gains', 'what if', 'sale', 'tax on sale'],
      },
      {
        id: 'taxes-whatif-override',
        title: 'Try a different input',
        where: 'Taxes → What-if',
        steps: [
          'Press **Add override** and pick an input — it starts at the stored value and changes nothing until you type a different one.',
          'Tick **Clear this input** to model the input cleared; a blank box never clears it.',
          'Or take a chip: **Max 401(k)**, **Max HSA — <tier>**, **Sell all <TICKER>**, **Realize gains to the 15% ceiling**.',
          'A shut chip says in its tooltip what has to be entered before it can size itself.',
        ],
        to: '/taxes?section=whatif',
        keywords: ['override', 'max 401k', 'scenario', 'what if input'],
      },
      {
        id: 'taxes-whatif-apply',
        title: 'Apply overrides to the stored year',
        where: 'Taxes → What-if',
        steps: [
          'Press **Apply <n> overrides to <year>** — a confirm lists every input before and after.',
          'Sale and ESPP legs are never written; only the override values reach the stored return.',
          'The Inputs view reloads on the write, discarding any unsaved edits it held.',
        ],
        to: '/taxes?section=whatif',
        keywords: ['apply overrides', 'write scenario'],
      },
    ],
    more: [
      {
        id: 'taxes-tables-clone',
        title: 'Clone tables into a married status',
        where: 'Taxes → Tax tables',
        steps: [
          'On the empty married tab, press **Clone from <year> single tables**.',
          'Then edit every table badged review thresholds; the ones badged copied verbatim are already right.',
        ],
        to: '/taxes?section=tables',
        keywords: ['clone tables', 'married tables'],
      },
      {
        id: 'taxes-per-person-table',
        title: 'Add a per-person payroll table',
        where: 'Taxes → Tax tables → Social Security · Disability',
        steps: [
          'Press **Add a table for <person>** — the draft is seeded from the default rows on screen.',
          'Edit the draft and press **Save**.',
          '**Discard draft** throws an unsaved draft away.',
          '**Remove — use the default** deletes a stored table; that person falls back to the default rows.',
        ],
        to: '/taxes?section=tables',
        keywords: ['per person', 'social security table', 'disability table'],
      },
      {
        id: 'taxes-derived-rows',
        title: 'Understand derived rows',
        where: 'Taxes → Inputs → Tax inputs',
        steps: [
          'A row badged derived shows the server’s figure and has no box — hover it for the formula.',
          'Edit its components instead; a write aimed at the total is refused and names them.',
        ],
        to: '/taxes?section=inputs',
      },
      {
        id: 'taxes-apply-vest',
        title: 'Bring vest income into the inputs',
        where: 'Taxes → Summary → Will I owe?',
        steps: [
          'Press the **Apply** chip beside the vest sentence.',
          'It writes the projected vest income to **W2: Stock/RSUs Sold** for the primary person.',
        ],
        to: '/taxes',
      },
      {
        id: 'taxes-pin',
        title: 'Pin and share a scenario',
        where: 'Taxes → What-if',
        steps: [
          'Type a name and press **Pin this scenario** — three per page, kept in this browser, knobs only.',
          '**Copy link** copies the live scenario’s address; a pin is never part of a link.',
        ],
        to: '/taxes?section=whatif',
      },
      {
        id: 'taxes-delete-year',
        title: 'Delete a tax year',
        where: 'Taxes → New tax year…',
        steps: [
          'Open **New tax year…**, press the delete entry, then confirm inside the popover.',
          'The year’s inputs and its bracket tables go with it.',
        ],
        to: '/taxes',
      },
      {
        id: 'taxes-marginal',
        title: 'Read the marginal ladder',
        where: 'Taxes → Summary → Marginal rates',
        steps: ['Enter this year’s **Federal** and **State** tables first — a jurisdiction without one is left off the ladder.'],
        to: '/taxes',
      },
    ],
    watch: [
      'The tab in Tax tables picks which tables you edit — editing a status the year is not filed under moves no totals.',
      'With no tables for the year’s status every figure reads as a dash rather than 0, and the summary offers the way in.',
      'Applying overrides is refused on a two-column year — a per-person input has to be edited in Tax inputs, which says which person.',
      'Deleting a tax year takes its inputs and its bracket tables with it, and cannot be undone.',
    ],
  },
]
