"""portfolio tables

Revision ID: ceeb7cd91a22
Revises: 1a11db65c138
Create Date: 2026-08-13 09:02:01.487438

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ceeb7cd91a22"
down_revision: str | Sequence[str] | None = "1a11db65c138"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "securities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("industry", sa.String(length=80), nullable=True),
        sa.Column("holding_type", sa.String(length=20), nullable=False),
        sa.Column("is_manual_priced", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("annual_dividend", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("ex_div_date", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_securities")),
        sa.UniqueConstraint("ticker", name=op.f("uq_securities_ticker")),
    )
    op.create_table(
        "dividend_payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("account", sa.String(length=80), nullable=True),
        sa.Column("pay_date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.id"],
            name=op.f("fk_dividend_payments_security_id_securities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dividend_payments")),
    )
    op.create_table(
        "latest_prices",
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("quoted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.id"],
            name=op.f("fk_latest_prices_security_id_securities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("security_id", name=op.f("pk_latest_prices")),
    )
    op.create_table(
        "position_transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("account", sa.String(length=80), nullable=False),
        sa.Column("type", sa.String(length=10), nullable=False),
        sa.Column("txn_date", sa.Date(), nullable=True),
        sa.Column("shares", sa.Numeric(precision=16, scale=6), nullable=False),
        sa.Column("price", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("fees", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("split_factor", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("sort_index", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.id"],
            name=op.f("fk_position_transactions_security_id_securities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_position_transactions")),
    )
    op.create_table(
        "price_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("price_date", sa.Date(), nullable=False),
        sa.Column("close", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.id"],
            name=op.f("fk_price_history_security_id_securities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_history")),
        sa.UniqueConstraint("security_id", "price_date", name=op.f("uq_price_history_security_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("price_history")
    op.drop_table("position_transactions")
    op.drop_table("latest_prices")
    op.drop_table("dividend_payments")
    op.drop_table("securities")
    # ### end Alembic commands ###
