"""widen tax input value to 4dp

Revision ID: a3f86e58ac4d
Revises: e301f88ed241
Create Date: 2026-08-13 22:31:39.046576

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a3f86e58ac4d"
down_revision: str | Sequence[str] | None = "e301f88ed241"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tax_inputs",
        "value",
        existing_type=sa.NUMERIC(precision=14, scale=2),
        type_=sa.Numeric(precision=14, scale=4),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tax_inputs",
        "value",
        existing_type=sa.Numeric(precision=14, scale=4),
        type_=sa.NUMERIC(precision=14, scale=2),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
