"""net worth and spending tables

Revision ID: 1a11db65c138
Revises: ff236c0c4a1e
Create Date: 2026-08-13 08:38:13.097987

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1a11db65c138"
down_revision: str | Sequence[str] | None = "ff236c0c4a1e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("group", sa.String(length=20), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accounts")),
        sa.UniqueConstraint("name", name=op.f("uq_accounts_name")),
        sa.UniqueConstraint("slug", name=op.f("uq_accounts_slug")),
    )
    op.create_table(
        "monthly_cashflow",
        sa.Column("month", sa.Date(), nullable=False),
        sa.Column("net_pay", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.PrimaryKeyConstraint("month", name=op.f("pk_monthly_cashflow")),
    )
    op.create_table(
        "net_worth_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("month", sa.Date(), nullable=False),
        sa.Column("recorded_on", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_net_worth_snapshots")),
        sa.UniqueConstraint("month", name=op.f("uq_net_worth_snapshots_month")),
    )
    op.create_table(
        "spending_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_spending_categories")),
        sa.UniqueConstraint("name", name=op.f("uq_spending_categories_name")),
        sa.UniqueConstraint("slug", name=op.f("uq_spending_categories_slug")),
    )
    op.create_table(
        "account_balances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("snapshot_id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("balance", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_account_balances_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["net_worth_snapshots.id"],
            name=op.f("fk_account_balances_snapshot_id_net_worth_snapshots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_account_balances")),
        sa.UniqueConstraint(
            "snapshot_id", "account_id", name=op.f("uq_account_balances_snapshot_id")
        ),
    )
    op.create_table(
        "monthly_spending",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("month", sa.Date(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["spending_categories.id"],
            name=op.f("fk_monthly_spending_category_id_spending_categories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_monthly_spending")),
        sa.UniqueConstraint("month", "category_id", name=op.f("uq_monthly_spending_month")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("monthly_spending")
    op.drop_table("account_balances")
    op.drop_table("spending_categories")
    op.drop_table("net_worth_snapshots")
    op.drop_table("monthly_cashflow")
    op.drop_table("accounts")
    # ### end Alembic commands ###
