"""comp and settings tables

Revision ID: e301f88ed241
Revises: 2558dac40530
Create Date: 2026-08-13 10:01:20.094266

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e301f88ed241"
down_revision: str | Sequence[str] | None = "2558dac40530"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_settings",
        sa.Column("key", sa.String(length=60), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_app_settings")),
    )
    op.create_table(
        "comp_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("focal_year", sa.Integer(), nullable=False),
        sa.Column("current_base", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("new_base", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("unvested_rsus", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("unvested_price", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("refresh_rsus", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("grant_price", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comp_events")),
        sa.UniqueConstraint("focal_year", name=op.f("uq_comp_events_focal_year")),
    )
    op.create_table(
        "espp_lots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("purchase_date", sa.Date(), nullable=False),
        sa.Column("qualifying_date", sa.Date(), nullable=False),
        sa.Column("shares", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("subscription_price", sa.Numeric(precision=14, scale=5), nullable=False),
        sa.Column("purchase_fmv", sa.Numeric(precision=14, scale=5), nullable=False),
        sa.Column("purchase_price", sa.Numeric(precision=14, scale=5), nullable=False),
        sa.Column("sold_date", sa.Date(), nullable=True),
        sa.Column("sold_price", sa.Numeric(precision=14, scale=5), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_espp_lots")),
        sa.UniqueConstraint("purchase_date", name=op.f("uq_espp_lots_purchase_date")),
    )
    op.create_table(
        "espp_periods",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=60), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("semi_annual_base", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("additional_payments", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("contribution_pct", sa.Numeric(precision=10, scale=9), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_espp_periods")),
        sa.UniqueConstraint("label", name=op.f("uq_espp_periods_label")),
    )
    op.create_table(
        "paycheck_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("annual_salary", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("pay_periods_per_year", sa.Integer(), nullable=False),
        sa.Column("trad_401k_pct", sa.Numeric(precision=10, scale=9), nullable=False),
        sa.Column("roth_401k_pct", sa.Numeric(precision=10, scale=9), nullable=False),
        sa.Column("after_tax_401k_pct", sa.Numeric(precision=10, scale=9), nullable=False),
        sa.Column("espp_pct", sa.Numeric(precision=10, scale=9), nullable=False),
        sa.Column("withholding_pct", sa.Numeric(precision=10, scale=9), nullable=False),
        sa.Column("dental_vision_per_check", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("hsa_per_check", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_paycheck_profiles")),
        sa.UniqueConstraint("effective_date", name=op.f("uq_paycheck_profiles_effective_date")),
    )
    op.create_check_constraint(
        op.f("ck_monthly_cashflow_month_is_first_of_month"),
        "monthly_cashflow",
        "EXTRACT(DAY FROM month) = 1",
    )
    op.create_check_constraint(
        op.f("ck_monthly_spending_month_is_first_of_month"),
        "monthly_spending",
        "EXTRACT(DAY FROM month) = 1",
    )
    op.create_check_constraint(
        op.f("ck_net_worth_snapshots_month_is_first_of_month"),
        "net_worth_snapshots",
        "EXTRACT(DAY FROM month) = 1",
    )
    # ### end Alembic commands ###

    # Hand-written: autogenerate is blind to autoincrement changes — it logs
    # tax_years_year_seq as "assuming SERIAL and omitting". tax_years.year is a natural key
    # (Task 9 review), so drop the SERIAL default: an omitted year must raise a not-null
    # violation, not silently insert a bogus year.
    op.alter_column("tax_years", "year", server_default=None)
    op.execute("DROP SEQUENCE IF EXISTS tax_years_year_seq")


def downgrade() -> None:
    """Downgrade schema."""
    # Hand-written mirror of the tax_years natural-key fix above (restore the SERIAL default).
    op.execute("CREATE SEQUENCE IF NOT EXISTS tax_years_year_seq OWNED BY tax_years.year")
    op.alter_column(
        "tax_years", "year", server_default=sa.text("nextval('tax_years_year_seq'::regclass)")
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_net_worth_snapshots_month_is_first_of_month"), "net_worth_snapshots", type_="check"
    )
    op.drop_constraint(
        op.f("ck_monthly_spending_month_is_first_of_month"), "monthly_spending", type_="check"
    )
    op.drop_constraint(
        op.f("ck_monthly_cashflow_month_is_first_of_month"), "monthly_cashflow", type_="check"
    )
    op.drop_table("paycheck_profiles")
    op.drop_table("espp_periods")
    op.drop_table("espp_lots")
    op.drop_table("comp_events")
    op.drop_table("app_settings")
    # ### end Alembic commands ###
