"""tax tables

Revision ID: 2558dac40530
Revises: ceeb7cd91a22
Create Date: 2026-08-13 09:22:47.389100

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2558dac40530"
down_revision: str | Sequence[str] | None = "ceeb7cd91a22"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tax_input_definitions",
        sa.Column("key", sa.String(length=60), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("section", sa.String(length=30), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_derived", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_tax_input_definitions")),
    )
    op.create_table(
        "tax_years",
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("year", name=op.f("pk_tax_years")),
    )
    op.create_table(
        "tax_brackets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("jurisdiction", sa.String(length=20), nullable=False),
        sa.Column("bracket_index", sa.Integer(), nullable=False),
        sa.Column("rate", sa.Numeric(precision=7, scale=4), nullable=False),
        sa.Column("threshold", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["year"],
            ["tax_years.year"],
            name=op.f("fk_tax_brackets_year_tax_years"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tax_brackets")),
        sa.UniqueConstraint(
            "year", "jurisdiction", "bracket_index", name=op.f("uq_tax_brackets_year")
        ),
    )
    op.create_table(
        "tax_inputs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=60), nullable=False),
        sa.Column("value", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["key"],
            ["tax_input_definitions.key"],
            name=op.f("fk_tax_inputs_key_tax_input_definitions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["year"],
            ["tax_years.year"],
            name=op.f("fk_tax_inputs_year_tax_years"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tax_inputs")),
        sa.UniqueConstraint("year", "key", name=op.f("uq_tax_inputs_year")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tax_inputs")
    op.drop_table("tax_brackets")
    op.drop_table("tax_years")
    op.drop_table("tax_input_definitions")
    # ### end Alembic commands ###
